### ISSUE TITLE
4. Run the demo app

### ISSUE THREAD

**Issue by kobuworks** [yas-sim/human-pose-estimation-2d-demo#1]
Hi yas-sim san,
Thanks a lot for your great works!!!!!
This is human-pose-estimation-2d.py demo. ;-)

4. Run the demo app
(Linux) python3 objdet-adaptive-partitioning.py
(Win10) python objdet-adaptive-partitioning.py

BR/Kobu

**Comment by yas-sim** [comment]
Kobu-san,

Thanks for reporting the error. I have corrected the error.

Regards,
Shimura
